# Generated by Django 5.2.11 on 2026-02-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrases', '0002_remove_phrase_description_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
    ]
