# Generated by Django 5.2.11 on 2026-02-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrases', '0003_fakeanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakeanswer',
            name='text',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
