# Generated by Django 5.2.11 on 2026-02-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrases', '0004_alter_fakeanswer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='translation',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
