# Generated by Django 5.2.11 on 2026-02-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrases', '0005_phrase_translation_delete_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='is_fake',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='translation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
