# Generated by Django 5.2.11 on 2026-02-16 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phrases', '0006_phrase_is_fake_alter_phrase_translation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FakeAnswer',
        ),
    ]
