# Generated by Django 5.2.11 on 2026-02-16 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phrases', '0007_delete_fakeanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phrase',
            name='next_send_at',
        ),
    ]
